# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ChemIITools',
                'doc_host': 'https://KGrewal1.github.io',
                'git_url': 'https://github.com/KGrewal1/ChemIITools',
                'lib_path': 'ChemIITools'},
  'syms': {'ChemIITools.core': {'ChemIITools.core.foo': ('core.html#foo', 'ChemIITools/core.py')}}}